# Generated by Django 3.1.1 on 2020-09-24 21:37

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command("loaddata", "vintages_data.json")


class Migration(migrations.Migration):

    dependencies = [
        ('MontalcinoForecastsApp', '0002_auto_20200923_2123'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
