# Generated by Django 3.1.1 on 2020-10-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('WineApp', '0013_auto_20190908_1839'),
        ('MontalcinoForecastsApp', '0003_auto_20200924_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vintage',
            unique_together={('year', 'wine')},
        ),
        migrations.CreateModel(
            name='ClimaticIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_montalcinoforecastsapp.climaticindex_set+', to='contenttypes.contenttype')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.sensor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
