# Generated by Django 3.1.1 on 2020-10-17 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MontalcinoForecastsApp', '0004_auto_20201017_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuglinIndex',
            fields=[
                ('climaticindex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MontalcinoForecastsApp.climaticindex')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('MontalcinoForecastsApp.climaticindex',),
        ),
        migrations.CreateModel(
            name='MonthsAvgIndex',
            fields=[
                ('climaticindex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MontalcinoForecastsApp.climaticindex')),
                ('start_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('end_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Months Avg indices',
            },
            bases=('MontalcinoForecastsApp.climaticindex',),
        ),
        migrations.CreateModel(
            name='WinklerIndex',
            fields=[
                ('climaticindex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MontalcinoForecastsApp.climaticindex')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('MontalcinoForecastsApp.climaticindex',),
        ),
    ]
