# Generated by Django 2.2.3 on 2019-07-25 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.IntegerField()),
                ('icon', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('precipitationType', models.CharField(max_length=200)),
                ('precipitationIntensity', models.FloatField()),
                ('precipitationIntensityMax', models.FloatField()),
                ('precipitationIntensityMaxTime', models.IntegerField()),
                ('precipitationProbability', models.FloatField()),
                ('precipitationAccumulation', models.FloatField()),
                ('uvIndex', models.IntegerField()),
                ('uvIndexTime', models.IntegerField()),
                ('sunriseTime', models.IntegerField()),
                ('sunsetTime', models.IntegerField()),
                ('temperatureMax', models.FloatField()),
                ('temperatureMin', models.FloatField()),
                ('apparentTemperatureMax', models.FloatField()),
                ('apparentTemperatureMin', models.FloatField()),
                ('windBearing', models.IntegerField()),
                ('apparentTemperatureMaxTime', models.IntegerField()),
                ('apparentTemperatureMinTime', models.IntegerField()),
                ('temperatureMinTime', models.IntegerField()),
                ('temperatureMaxTime', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('cloudCover', models.FloatField()),
                ('dewPoint', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('moonPhase', models.FloatField()),
                ('pressure', models.FloatField()),
                ('visibility', models.FloatField()),
                ('temperatureHigh', models.FloatField()),
                ('temperatureLow', models.FloatField()),
                ('temperatureHighTime', models.IntegerField()),
                ('temperatureLowTime', models.IntegerField()),
                ('apparentTemperatureHigh', models.FloatField()),
                ('apparentTemperatureLow', models.FloatField()),
                ('apparentTemperatureHighTime', models.IntegerField()),
                ('apparentTemperatureLowTime', models.IntegerField()),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.Wine')),
            ],
        ),
        migrations.CreateModel(
            name='VintageRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0),
                                                         django.core.validators.MinValueValidator(1.0)])),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.Wine')),
            ],
        ),
    ]
