# Generated by Django 2.2.3 on 2019-08-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.Sensor')),
            ],
            options={
                'unique_together': {('time', 'sensor')},
            },
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg', models.FloatField(blank=True, default=None, null=True)),
                ('min', models.FloatField(blank=True, default=None, null=True)),
                ('max', models.FloatField(blank=True, default=None, null=True)),
                ('minTime', models.TimeField(blank=True, default=None, null=True)),
                ('maxTime', models.TimeField(blank=True, default=None, null=True)),
                ('tot', models.FloatField(blank=True, default=None, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.Sensor')),
            ],
            options={
                'unique_together': {('date', 'sensor')},
            },
        ),
    ]
