# Generated by Django 2.2.3 on 2019-08-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='icon',
            field=models.CharField(default='nulla', max_length=50),
            preserve_default=False,
        ),
    ]
