# Generated by Django 2.2.3 on 2019-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperatureAvg', models.FloatField()),
                ('temperatureMax', models.FloatField()),
                ('temperatureMin', models.FloatField()),
                ('humidityAvg', models.FloatField()),
                ('humidityMax', models.FloatField()),
                ('humidityMin', models.FloatField()),
                ('dewPointAvg', models.FloatField(blank=True, default=None, null=True)),
                ('dewPointMax', models.FloatField(blank=True, default=None, null=True)),
                ('dewPointMin', models.FloatField(blank=True, default=None, null=True)),
                ('upperLeafWetnessHours', models.FloatField(blank=True, default=None, null=True)),
                ('upperLeafWetnessMax', models.FloatField(blank=True, default=None, null=True)),
                ('upperLeafWetnessMin', models.FloatField(blank=True, default=None, null=True)),
                ('lowerLeafWetnessHours', models.FloatField(blank=True, default=None, null=True)),
                ('lowerLeafWetnessMax', models.FloatField(blank=True, default=None, null=True)),
                ('lowerLeafWetnessMin', models.FloatField(blank=True, default=None, null=True)),
                ('rain', models.FloatField()),
                ('windSpeedAvg', models.FloatField()),
                ('windSpeedMax', models.FloatField()),
                ('windDirection', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='weatherhistory',
            old_name='day',
            new_name='date',
        ),
    ]
