# Generated by Django 2.2.3 on 2019-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineApp', '0002_sensor_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='activeFrom',
        ),
        migrations.AddField(
            model_name='sensor',
            name='startTestSet',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
