# Generated by Django 2.2.3 on 2019-07-27 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0003_dailysensordata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='humidityAvg',
            new_name='airHumidityAvg',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='humidityMax',
            new_name='airHumidityMax',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='humidityMin',
            new_name='airHumidityMin',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='temperatureAvg',
            new_name='airTemperatureAvg',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='temperatureMax',
            new_name='airTemperatureMax',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='temperatureMin',
            new_name='airTemperatureMin',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='rain',
            new_name='rainAvg',
        ),
        migrations.RenameField(
            model_name='sensorhistory',
            old_name='windDirection',
            new_name='windDirectionAvg',
        ),
    ]
