# Generated by Django 2.2.3 on 2019-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0003_auto_20190812_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
