# Generated by Django 2.2.3 on 2019-08-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0006_predictionmethod_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='var',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
