# Generated by Django 2.2.3 on 2019-08-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0008_prediction_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmethod',
            name='defaultParams',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='PredictionParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(default='')),
                ('method',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.PredictionMethod')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WineApp.Sensor')),
            ],
        ),
    ]
