# Generated by Django 2.2.3 on 2019-08-22 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0009_auto_20190822_1804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predictionparams',
            unique_together={('sensor', 'method')},
        ),
    ]
