# Generated by Django 2.2.3 on 2019-09-05 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WineApp', '0011_auto_20190905_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='hourlyTable',
            new_name='table',
        ),
        migrations.DeleteModel(
            name='RealTimeData',
        ),
    ]
