# Generated by Django 2.2.3 on 2019-09-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WineApp', '0012_auto_20190905_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VintageRating',
        ),
        migrations.DeleteModel(
            name='WeatherHistory',
        ),
    ]
